-- TABLAS DEL MÓDULO app-books
CREATE TABLE book (
                      isbn VARCHAR(255) NOT NULL,
                      title VARCHAR(255),
                      price DOUBLE PRECISION,
                      version INTEGER,
                      CONSTRAINT pk_book PRIMARY KEY (isbn)
);

CREATE TABLE inventory (
                           book_isbn VARCHAR(255) NOT NULL,
                           sold INTEGER,
                           supplied INTEGER,
                           version INTEGER,
                           CONSTRAINT pk_inventory PRIMARY KEY (book_isbn),
                           CONSTRAINT fk_inv_book FOREIGN KEY (book_isbn) REFERENCES book(isbn)
);



-- TABLAS DEL MÓDULO app-customers
CREATE TABLE customer (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                          name VARCHAR(255),
                          email VARCHAR(255),
                          version INTEGER,
                          CONSTRAINT pk_customer PRIMARY KEY (id)
);

CREATE TABLE purchaseorder (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                               customer_id BIGINT,
                               deliveredon TIMESTAMP,
                               placedon TIMESTAMP,
                               status INTEGER,
                               total INTEGER,
                               CONSTRAINT pk_purchaseorder PRIMARY KEY (id),
                               CONSTRAINT fk_po_customer FOREIGN KEY (customer_id) REFERENCES customer(id)
);

CREATE TABLE lineitem (
                          order_id BIGINT NOT NULL,
                          idx INTEGER NOT NULL,
                          book_isbn VARCHAR(255),
                          quantity INTEGER,
                          CONSTRAINT pk_lineitem PRIMARY KEY (order_id, idx),
                          CONSTRAINT fk_li_order FOREIGN KEY (order_id) REFERENCES purchaseorder(id),
                          CONSTRAINT fk_li_book FOREIGN KEY (book_isbn) REFERENCES book(isbn)
);